### ISSUE TITLE
Files within directories are not being analyzed

### ISSUE THREAD

**Issue by filipesperandio** [mercos/codeclimate-flake8#2]
I noticed while testing that it is only looking at files in the root directory, might be something you wanna takle after. It should go recursively into the base directory looking at all files.

**Comment by jklemm** [comment]
Nice, I'll change this behavior.

**Comment by filipesperandio** [comment]
Might be worth checking out the analyzer spec if you haven't, specially the part about files.
https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#which-files-to-analyze
